### ISSUE TITLE
[Errors] when running "npm run test"

### ISSUE THREAD

**Issue by field0917** [rwieruch/favesound-mobx#10]
The following error will occur when running `npm run test`: 
`react-addons-test-utils is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation`

**Comment by rwieruch** [comment]
Could this be related to https://github.com/rwieruch/favesound-mobx/pull/7 or https://github.com/rwieruch/favesound-mobx/pull/8 ?

**Comment by field0917** [comment]
I think so, I'll give it a try!

**Comment by field0917** [comment]
PR #12
