### ISSUE TITLE
[Bug]: Song title overflow in player queue

### ISSUE THREAD

**Issue by field0917** [rwieruch/favesound-mobx#11]
<img width="380" alt="screen shot 2017-06-20 at 1 51 45 pm" src="https://user-images.githubusercontent.com/19654067/27355398-bd1f629a-55bf-11e7-9ab5-72c9ddd5bd92.png">

**Comment by rwieruch** [comment]
I think that's ok, since it only shows the icons on hover or when the song is active. Otherwise it is good that the text uses the whole space. What do you think?

**Comment by field0917** [comment]
Cool! That sounds good to me!
