### ISSUE TITLE
if login rejected

### ISSUE THREAD

**Issue by milon87** [rwieruch/favesound-mobx#13]
I was checking live demo. after login button press it was trying to navigate to the dashboard but login was not successful. so it was stuck in the dashboard with a loading indicator. 

I think if login rejects/cancel then it will show only home page.

**Comment by rwieruch** [comment]
Yes. I have seen this issue too. 

Apparently it is also an issue in https://github.com/rwieruch/favesound-redux I wouldn't want to diverge both repositories too much from each other. If it keeps being an issue for people, it would be great to address it first in the big brother favesound-redux project.

**Comment by chriszhangusc** [comment]
@rwieruch I have created a PR for this issue in favesound-redux.

**Comment by chriszhangusc** [comment]
@rwieruch Do you think I should also update this repo too to keep it in sync with favesound-redux?
https://github.com/rwieruch/favesound-redux/issues/77

**Comment by rwieruch** [comment]
If you have the time, I think it would be great to keep them in sync :)
 This one can be closed right?

**Comment by chriszhangusc** [comment]
@rwieruch Sure, I'll do it. I think it could be closed afterward.
