### ISSUE TITLE
Upgrade to React 16

### ISSUE THREAD

**Issue by rwieruch** [rwieruch/favesound-mobx#14]
React 16 got [released](https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html) and there are practically no changes to the external API of React. Perhaps it would be an easy win to upgrade the project to React 16. Someone keen to do it?

**Comment by Ernoff** [comment]
Yeah I will handle it

**Comment by Ernoff** [comment]
Updating React and React-dom to v16.0.0 breaks test. Enzyme does not support the latest react version at the moment. Do I still go ahead with the Upgrade??

**Comment by rwieruch** [comment]
Isn't there a new version for Enzyme as well? Otherwise I would think a lot of people would run into this issue, wouldn't they? Thanks for solving this issue! :)

**Comment by Ernoff** [comment]
There is a new version of Enzyme as well v3.0. A whole lot of warnings still popping up. Am still on it though

**Comment by rwieruch** [comment]
Hello @Ernoff Maybe you can cross check with this PR (https://github.com/rwieruch/favesound-redux/pull/71) where a great contributor of the repository just updated the favesound-redux equivalent to React 16. Thanks to your findings, I was able to point out the Enzyme change in this equivalent repositories. 👍

**Comment by rwieruch** [comment]
@Ernoff this https://github.com/rwieruch/favesound-redux/pull/72 should be the final PR for the equivalent repository. Maybe it helps you to migrate this one too 🎉

**Comment by Ernoff** [comment]
@rwieruch It just worked!!! Update was done and tests are presently working seamlessly.
